/**
 * \file Ifx_Cfg.h
 * \brief Project configuration file.
 *
 * \copyright Copyright (c) 2018 Infineon Technologies AG. All rights reserved.
 *
 *
 *
 *                                 IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.

 *
 */

#ifndef IFX_CFG_H
#define IFX_CFG_H 1
/******************************************************************************/

/*______________________________________________________________________________
** Configuration for IfxScu_cfg.h
**____________________________________________________________________________*/
#define IFX_CFG_SCU_XTAL_FREQUENCY		(20000000)	/**< */
#define IFX_CFG_SCU_PLL_FREQUENCY		(300000000) /**< */

/*______________________________________________________________________________
** Configuration for Software managed interrupt
**____________________________________________________________________________*/

//#define IFX_USE_SW_MANAGED_INT

/*______________________________________________________________________________
** Configuration for Trap Hook Functions' Extensions
**____________________________________________________________________________*/

//#define IFX_CFG_EXTEND_TRAP_HOOKS

/*______________________________________________________________________________
** Configuration CPU enable / disable
**____________________________________________________________________________*/

#define IFX_CFG_SSW_ENABLE_TRICORE0   (1U)
#define IFX_CFG_SSW_ENABLE_TRICORE1   (1U)
#define IFX_CFG_SSW_ENABLE_TRICORE2   (1U)
#define IFX_CFG_SSW_ENABLE_TRICORE3   (1U)
#define IFX_CFG_SSW_ENABLE_TRICORE4   (1U)
#define IFX_CFG_SSW_ENABLE_TRICORE5   (1U)

/*______________________________________________________________________________
** Constant which for CPU Synchronization Event
**____________________________________________________________________________*/
#define IFXCPU_CFG_ALLCORE_DONE (             \
        (IFX_CFG_SSW_ENABLE_TRICORE0 << 0U) | \
        (IFX_CFG_SSW_ENABLE_TRICORE1 << 1U) | \
        (IFX_CFG_SSW_ENABLE_TRICORE2 << 2U) | \
        (IFX_CFG_SSW_ENABLE_TRICORE3 << 3U) | \
        (IFX_CFG_SSW_ENABLE_TRICORE4 << 4U) | \
        (IFX_CFG_SSW_ENABLE_TRICORE5 << 6U))



/*______________________________________________________________________________
** Configuration for CPU Caches enable / disable
**____________________________________________________________________________*/

#define IFX_CFG_SSW_ENABLE_TRICORE0_PCACHE  1
#define IFX_CFG_SSW_ENABLE_TRICORE0_DCACHE  1
#define IFX_CFG_SSW_ENABLE_TRICORE1_PCACHE  1
#define IFX_CFG_SSW_ENABLE_TRICORE1_DCACHE  1
#define IFX_CFG_SSW_ENABLE_TRICORE2_PCACHE  1
#define IFX_CFG_SSW_ENABLE_TRICORE2_DCACHE  1
#define IFX_CFG_SSW_ENABLE_TRICORE3_PCACHE  1
#define IFX_CFG_SSW_ENABLE_TRICORE3_DCACHE  1
#define IFX_CFG_SSW_ENABLE_TRICORE4_PCACHE  1
#define IFX_CFG_SSW_ENABLE_TRICORE4_DCACHE  1
#define IFX_CFG_SSW_ENABLE_TRICORE5_PCACHE  1
#define IFX_CFG_SSW_ENABLE_TRICORE5_DCACHE  1

/******************************************************************************/

#endif /* IFX_CFG_H */
